
    create table HIERARCHY_NODE (
        ID bigint generated by default as identity (start with 1),
        directParentIds varchar(2000),
        parentIds varchar(4000),
        directChildIds varchar(2000),
        childIds varchar(4000),
        primary key (ID)
    );

    create table HIERARCHY_NODE_META (
        ID bigint generated by default as identity (start with 1),
        hierarchyId varchar(255),
        isRootNode bit not null,
        ownerId varchar(255),
        title varchar(255),
        description longvarchar,
        permToken varchar(255),
        primary key (ID)
    );

    create index HIERARCHY_HID on HIERARCHY_NODE_META (hierarchyId);

    create index HIERARCHY_PERMTOKEN on HIERARCHY_NODE_META (permToken);
